services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001" --quiet
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data

  app:
    build: .
    env_file: config.env
    ports:
      - "8080:8080"
    depends_on:
      - minio
      - kafka
    stop_grace_period: 5s


volumes:
  minio_data: